name: ðŸ› Bug Report
description: Report a bug or unexpected behavior in Task-Tracker-Pro
labels: ['bug', 'triage']
assignees: ['VoxDroid']
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for taking the time to report a bug!

        Please fill out this form as completely as possible to help us diagnose and fix the issue quickly.
        Before submitting, please search existing issues to avoid duplicates.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following before submitting your report.
      options:
        - label: I have searched existing [issues](https://github.com/VoxDroid/Task-Tracker-Pro/issues) and this bug has not been reported.
          required: true
        - label: I am using the latest version of Task-Tracker-Pro.
          required: true
        - label: I have read the project documentation and this is not expected behavior.
          required: true

  - type: dropdown
    id: app-type
    attributes:
      label: Application Type
      description: Are you using the web version or the desktop (Electron) application?
      options:
        - Desktop App (Electron)
        - Web Browser (Next.js)
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: |
        Example: When I try to create a new task with a due date in the past, the application crashes without any error message.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed, numbered steps to reproduce the issue.
      placeholder: |
        1. Open the application
        2. Navigate to 'Tasks' page
        3. Click 'Add New Task' button
        4. Fill in the task details with...
        5. Click 'Save'
        6. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        Example: The task should be created successfully and appear in the task list.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: |
        Example: The application shows a blank screen and the task is not saved.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma (14.x)
        - macOS Ventura (13.x)
        - macOS (older)
        - Ubuntu/Debian Linux
        - Fedora/RHEL Linux
        - Arch Linux
        - Other Linux
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Task-Tracker-Pro Version
      description: What version of Task-Tracker-Pro are you using? (Check in Settings or About)
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if applicable)
      description: If running from source, what version of Node.js are you using?
      placeholder: e.g., v20.10.0
    validations:
      required: false

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the application is affected?
      multiple: true
      options:
        - Dashboard
        - Tasks Management
        - Projects Management
        - Time Tracking
        - Archive
        - Settings
        - Search Functionality
        - Database Operations (Import/Export/Reset)
        - Activity Logs
        - UI/Styling
        - Navigation/Sidebar
        - Notifications
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Major feature is broken
        - Medium - Feature works but with issues
        - Low - Minor inconvenience or cosmetic issue
      default: 2
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: If applicable, add screenshots or screen recordings to help explain the problem.
      placeholder: Drag and drop images here, or paste them directly...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Console Output
      description: |
        If available, paste any error messages or console output here.
        For Electron: View > Toggle Developer Tools > Console
        For Web: Browser DevTools (F12) > Console
      placeholder: |
        Paste error messages or console output here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem, such as recent changes or workarounds you've tried.
      placeholder: |
        Example: This started happening after I imported data from a backup. I tried clearing the database but the issue persists.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing a fix?
      options:
        - label: I would be willing to submit a pull request to fix this bug.
          required: false
